app: Disable OnboardWindow
I disabled the boarding window due to the following error

Traceback (most recent call last):
  File "/app/share/aviator/aviator/main.py", line 123, in go
    app.win = MainWindow(application=app)
                                     ^^^
NameError: name 'app' is not defined